name: "\U0001F41E Bug report"
description: Report an issue with Svelte
labels: ['triage: bug']
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this bug report!
  - type: textarea
    id: bug-description
    attributes:
      label: Describe the bug
      description: A clear and concise description of what the bug is. If you intend to submit a PR for this issue, tell us in the description. Thanks!
      placeholder: Bug description
    validations:
      required: true
  - type: textarea
    id: reproduction
    attributes:
      label: Reproduction
      description: Please provide th steps to reproduce the bug.
      value: |
      1. Go to '...'
      2. Click on '....'
      3. Scroll down to '....'
      4. See error
    validations:
      required: true
  - type: textarea
    id: system-info
    attributes:
      label: System Info
      description: Please provide the system information the bug occured on.
      render: shell
      value: |
      - OS: [e.g. Windows, Linux]
      - Browser [e.g. Firefox, Chrome]
      - Version [e.g. 22]
    validations:
      required: true
